apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
stringData:
  jwt: "796929470986f48c2d46d0dbc56743da"
  mongo-username: "omartankary"
  mongo-password: "omartest"
  mongo-uri: "mongodb://admin:admin@mongodb:27017/chatdb?authSource=admin"

